# toast
spring:
  profiles: toast
  redis:
    host: 10.210.24.30
  datasource:
    jdbc-url: jdbc:sqlserver://10.210.24.204;databaseName=FG_V2
  datasource2:
    jdbc-url: jdbc:sqlserver://10.210.24.204;databaseName=FG_PAY
  datasource3:
    jdbc-url: jdbc:sqlserver://10.210.24.204;databaseName=FG_EM
  datasource4:
    jdbc-url: jdbc:sqlserver://10.210.24.204;databaseName=FG_PhotoStudio
  
  jpa:
    show-sql: false
    properties.hibernate.format_sql: false
    properties.hibernate.generate_statistics: false
    
webAdminapi:
  fgServiceAPI_EndPoint: http://10.210.8.153
  
server:
  port: 19901

logging:
  config: classpath:log4j2-toast.xml
  path: /home1/irteam/logs/

photostudio:
  fullModelPackageIdMap:
    package1: 1, 7, 18
    package2: 2, 8, 19
    package3: 3, 9, 20
  reportTypeProperties:
    test: test
    categoryIdMap:
      FullModelShotWomen: 1, 5
      FullModelShotWomenPlusSize: 2, 6
      FlatProductShotMen: 3, 7
      FlatProductShotKids: 4, 7
      FlatProductShotShoes: 7
      FlatProductShotHandbags: 7
      FlatProductShotAccessories: 7
    packageIdMap:
      FullModelShotWomen: 1, 2, 3, 7, 8, 9, 18, 19, 20
      FullModelShotWomenPlusSize: 1, 2, 3, 7, 8, 9, 18, 19, 20
      FlatProductShotMen: 12
      FlatProductShotKids: 13
      FlatProductShotShoes: 14
      FlatProductShotHandbags: 15
      FlatProductShotAccessories: 16

toast:
  cloud:
    storage:
      object-storage:
        account: AUTH_d2a2372095f2462da8b883294f747273
        tenant-id: d2a2372095f2462da8b883294f747273
        username: dl_nhnglobal_tc_service@nhnglobal.com
        password: FG!@#123
        auth-api-url: https://api-compute.cloud.toast.com/identity/v2.0/tokens
        api-url: https://api-storage.cloud.toast.com/v1/

coupon:
  notification:
    storage:
      root-email-name: coupon-email-list
      root-image-name: coupon-banner-images
      root-name-prefix: ""
    image-root: https://rlzwrhbmy.cdn.toastcloud.com/
