# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# (http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html)
# ===================================================================

spring:
  application:
    name: FashionGo WebAdminAPI
  profiles:
    active: "local"
  # Primary DB
  datasource:
    username: FGWebAdminAPIUser
    password: APIUser6301
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # Connection pool for Primary DB
    type: org.apache.commons.dbcp2.BasicDataSource #datasource connection pool 세부 설정 추가 필요함
    dbcp2:
      max-wait-millis: 3000
      max-total: 50
      initial-size: 20
      test-on-borrow : true
      test-on-return : true
      test-while-idle : true
      validation-query : select 1
      validation-query-timeout: 1 # one second
      time-between-eviction-runs-millis: 60000 # one minute
      num-tests-per-eviction-run: 3
      min-evictable-idle-time-millis: 600000 # ten minutes
      pool-prepared-statements: true
      default-query-timeout: 15 # 15 seconds
  datasource2:
    username: FGWebAdminAPIUser
    password: APIUser6301
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # Connection pool for FG Pay DB
    type: org.apache.commons.dbcp2.BasicDataSource #datasource connection pool 세부 설정 추가 필요함
    dbcp2:
      max-wait-millis: 3000
      max-total: 50
      initial-size: 10
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      validation-query: select 1
      validation-query-timeout: 1 # one second
      time-between-eviction-runs-millis: 60000 # one minute
      num-tests-per-eviction-run: 3
      min-evictable-idle-time-millis: 600000 # ten minutes
      pool-prepared-statements: true
      default-query-timeout: 15 # 15 seconds
  # FG EM DB
  datasource3:
    username: FGWebAdminAPIUser
    password: APIUser6301
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # Connection pool for FG EM DB
    type: org.apache.commons.dbcp2.BasicDataSource #datasource connection pool 세부 설정 추가 필요함
    dbcp2:
      max-wait-millis: 3000
      max-total: 30
      initial-size: 10
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      validation-query: select 1
      validation-query-timeout: 1 # one second
      time-between-eviction-runs-millis: 60000 # one minute
      num-tests-per-eviction-run: 3
      min-evictable-idle-time-millis: 600000 # ten minutes
      pool-prepared-statements: true
      default-query-timeout: 15 # 15 seconds
  # FG PhtoStudio DB
  datasource4:
    username: FGWebAdminAPIUser
    password: APIUser6301
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # Connection pool for FG PhtoStudio DB
    type: org.apache.commons.dbcp2.BasicDataSource #datasource connection pool 세부 설정 추가 필요함
    dbcp2:
      max-wait-millis: 3000
      max-total: 30
      initial-size: 10
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      validation-query: select 1
      validation-query-timeout: 1 # one second
      time-between-eviction-runs-millis: 60000 # one minute
      num-tests-per-eviction-run: 3
      min-evictable-idle-time-millis: 600000 # ten minutes
      pool-prepared-statements: true
      default-query-timeout: 15 # 15 seconds
  # FG Billing DB
  datasource5:
    username: FGWebAdminAPIUser
    password: APIUser6301
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # Connection pool for FG Billing DB
    type: org.apache.commons.dbcp2.BasicDataSource #datasource connection pool 세부 설정 추가 필요함
    dbcp2:
      max-wait-millis: 3000
      max-total: 30
      initial-size: 10
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      validation-query: select 1
      validation-query-timeout: 1 # one second
      time-between-eviction-runs-millis: 60000 # one minute
      num-tests-per-eviction-run: 3
      min-evictable-idle-time-millis: 600000 # ten minutes
      pool-prepared-statements: true
      default-query-timeout: 15 # 15 seconds
  # FG Stats DB
  datasource6:
    username: FGWebAdminAPIUser
    password: APIUser6301
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # Connection pool for FG Stats DB
    type: org.apache.commons.dbcp2.BasicDataSource #datasource connection pool 세부 설정 추가 필요함
    dbcp2:
      max-wait-millis: 3000
      max-total: 30
      initial-size: 10
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      validation-query: select 1
      validation-query-timeout: 1 # one second
      time-between-eviction-runs-millis: 60000 # one minute
      num-tests-per-eviction-run: 3
      min-evictable-idle-time-millis: 600000 # ten minutes
      pool-prepared-statements: true
      default-query-timeout: 15 # 15 seconds
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
    properties.hibernate.generate_statistics: false
    properties.javax.persistence.query.timeout: 10000
    properties.hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate.naming.physical-strategy: net.fashiongo.common.dal.MSSQLServerNamingStrategy
  cache:
    type: redis
    redis:
      time-to-live: 18000000 # expries after 30 min
  redis:
    host: 10.210.16.201
    port: 6379
    database: 2
    
    
server:
  port: 29901
  servlet:
    context-path: /api
  tomcat:
    basedir: .
    max-threads: 250
    min-spare-threads: 10
    remote-ip-header: "X-Forwarded-For"
    accesslog:
      enabled: true
      suffix: .log
      prefix: access_log
      file-date-format: .yyyy-MM-dd
      directory: /home1/irteam/logs/webadmin_api/accesslog
      pattern: "%{org.apache.catalina.AccessLog.RemoteAddr}r %l %u %t \"%r\" %s %b %D \"%{Referer}i\" \"%{User-Agent}i\" %{X-Request-Id}i %I"
#      pattern: combined

webAdminapi:
  fgServiceAPI_EndPoint: http://10.210.16.205:29001
  fgVendorAPI_EndPoint: http://10.210.16.205:28501
  fgWebAdminAPI_EndPoint: http://webadmin-api-staging.fashiongo.net/api/
  statsAPI_EndPoint: http://10.210.16.203:27601
  adapi:
    endpoint: http://10.210.16.205:18000
  productApi:
    endpoint: http://10.210.16.205:17301
  rewardApi:
    endpoint: http://localhost:17401/v1
  jwt:
    develop:
      check-token: true
  fashionGoApi:
      endpoint: http://10.210.16.205:17301

bid-redis:
  database: 3
  lock:
    timeout-seconds:
      acquire: 3
      expire: 10

management:
  endpoints:
    web:
      exposure:
        include: l7check
      base-path: /monitor
---
# Local
spring:
  profiles: local
  redis:
    host: 10.210.16.201
  datasource:
    url: jdbc:sqlserver://10.210.16.31;databaseName=FG_V2
    dbcp2:
      maxTotal: 10
  datasource2:
    url: jdbc:sqlserver://10.210.16.31;databaseName=FG_PAY
    dbcp2:
      maxTotal: 10
  datasource3:
    url: jdbc:sqlserver://10.210.16.31;databaseName=FG_EM
    dbcp2:
      maxTotal: 10
  datasource4:
    url: jdbc:sqlserver://10.210.16.31;databaseName=FG_PhotoStudio
    dbcp2:
      maxTotal: 10
  datasource5:
    url: jdbc:sqlserver://10.210.16.31;databaseName=FG_Billing
    dbcp2:
      maxTotal: 10
  datasource6:
    url: jdbc:sqlserver://10.210.16.31;databaseName=FG_Stats
    dbcp2:
      maxTotal: 10

logging:
  config: classpath:logback-spring.xml
  path: logs/webadmin_api/
  level:
    sql: TRACE
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
#              BasicExtractor: TRACE

webAdminapi:
  fgServiceAPI_EndPoint: http://10.210.16.205:29001
  fgPaymentAPI_EndPoint: http://10.210.16.205:29201
  rewardApi:
    endpoint: http://10.210.16.205:17401/v1
  jwt:
    develop:
      check-token: true

photostudio:
  fullModelPackageIdMap:
    package1: 1, 7, 18
    package2: 2, 8, 19
    package3: 3, 9, 20
  reportTypeProperties:
    test: test
    categoryIdMap:
      FullModelShotWomen: 1, 5
      FullModelShotWomenPlusSize: 2, 6
      FlatProductShotMen: 3, 7
      FlatProductShotKids: 4, 7
      FlatProductShotShoes: 7
      FlatProductShotHandbags: 7
      FlatProductShotAccessories: 7
    packageIdMap:
      FullModelShotWomen: 1, 2, 3, 7, 8, 9, 18, 19, 20
      FullModelShotWomenPlusSize: 1, 2, 3, 7, 8, 9, 18, 19, 20
      FlatProductShotMen: 12
      FlatProductShotKids: 13
      FlatProductShotShoes: 14
      FlatProductShotHandbags: 15
      FlatProductShotAccessories: 16

toast:
  cloud:
    storage:
      object-storage:
        account: AUTH_7e2eaaa493ce4625a815481da0ec2e1a
        tenant-id: 7e2eaaa493ce4625a815481da0ec2e1a
        username: dl_nhnglobal_tc_service@nhnglobal.com
        password: FG!@#123
        auth-api-url: https://api-compute.cloud.toast.com/identity/v2.0/tokens
        api-url: https://api-storage.cloud.toast.com/v1/

coupon:
  notification:
    storage:
      root-email-name: coupon-email-list
      root-image-name: coupon-banner-images
      root-name-prefix: dev-
    image-root: https://rlyfpniry.toastcdn.net/

gnb:
  banner:
    image:
      storage:
        object-storage:
          account: AUTH_d2a2372095f2462da8b883294f747273
          tenant-id: d2a2372095f2462da8b883294f747273
          username: dl_nhnglobal_tc_service@nhnglobal.com
          password: FG!@#123
          auth-api-url: https://api-compute.cloud.toast.com/identity/v2.0/tokens
          api-url: https://api-storage.cloud.toast.com/v1/
        root-container: 'production'
        directory: 'gnb-menu-banner-img'

server:
  tomcat:
    accesslog:
      directory: logs/
