# beta
spring:
  profiles: beta
  redis:
    host: 10.10.0.145
  datasource:
    jdbc-url: jdbc:sqlserver://10.200.24.29;databaseName=FG_V2
  datasource2:
    jdbc-url: jdbc:sqlserver://10.200.24.29;databaseName=FG_PAY
  datasource3:
    jdbc-url: jdbc:sqlserver://10.200.24.29;databaseName=FG_EM
  datasource4:
    jdbc-url: jdbc:sqlserver://10.200.24.29;databaseName=FG_PhotoStudio
    
  jpa:
    show-sql: false
    properties.hibernate.format_sql: false
    properties.hibernate.generate_statistics: false

webAdminapi:
  fgServiceAPI_EndPoint: http://10.10.0.32:29021
    
logging:
  config: classpath:log4j2-beta.xml

bid-redis:
  database: 4

photostudio:
  fullModelPackageIdMap:
    package1: 1, 7, 18
    package2: 2, 8, 19
    package3: 3, 9, 20
  reportTypeProperties:
    test: test
    categoryIdMap:
      FullModelShotWomen: 1, 5
      FullModelShotWomenPlusSize: 2, 6
      FlatProductShotMen: 3, 7
      FlatProductShotKids: 4, 7
      FlatProductShotShoes: 7
      FlatProductShotHandbags: 7
      FlatProductShotAccessories: 7
    packageIdMap:
      FullModelShotWomen: 1, 2, 3, 7, 8, 9, 18, 19, 20
      FullModelShotWomenPlusSize: 1, 2, 3, 7, 8, 9, 18, 19, 20
      FlatProductShotMen: 12
      FlatProductShotKids: 13
      FlatProductShotShoes: 14
      FlatProductShotHandbags: 15
      FlatProductShotAccessories: 16
