# Stage
spring:
  profiles: stage
  redis:
    host: 10.10.0.145
  datasource:
    jdbc-url: jdbc:sqlserver://10.200.16.33;databaseName=FG_V2
  datasource2:
    jdbc-url: jdbc:sqlserver://10.200.16.33;databaseName=FG_PAY
  datasource3:
    jdbc-url: jdbc:sqlserver://10.200.16.33;databaseName=FG_EM
  datasource4:
    jdbc-url: jdbc:sqlserver://10.200.16.33;databaseName=FG_PhotoStudio
    
  jpa:
    show-sql: false
    properties.hibernate.format_sql: false
    properties.hibernate.generate_statistics: false

webAdminapi:
  fgServiceAPI_EndPoint: http://10.10.0.145:29011
  statsAPI_EndPoint: http://10.10.0.145:19101
    
logging:
  config: classpath:log4j2-stage.xml

bid-redis:
  database: 4

photostudio:
  fullModelPackageIdMap:
    package1: 1, 7, 18
    package2: 2, 8, 19
    package3: 3, 9, 20
  reportTypeProperties:
    test: test
    categoryIdMap:
      FullModelShotWomen: 1, 5
      FullModelShotWomenPlusSize: 2, 6
      FlatProductShotMen: 3, 7
      FlatProductShotKids: 4, 7
      FlatProductShotShoes: 7
      FlatProductShotHandbags: 7
      FlatProductShotAccessories: 7
    packageIdMap:
      FullModelShotWomen: 1, 2, 3, 7, 8, 9, 18, 19, 20
      FullModelShotWomenPlusSize: 1, 2, 3, 7, 8, 9, 18, 19, 20
      FlatProductShotMen: 12
      FlatProductShotKids: 13
      FlatProductShotShoes: 14
      FlatProductShotHandbags: 15
      FlatProductShotAccessories: 16

toast:
  cloud:
    storage:
      object-storage:
        account: AUTH_7e2eaaa493ce4625a815481da0ec2e1a
        tenant-id: 7e2eaaa493ce4625a815481da0ec2e1a
        username: dl_nhnglobal_tc_service@nhnglobal.com
        password: FG!@#123
        auth-api-url: https://api-compute.cloud.toast.com/identity/v2.0/tokens
        api-url: https://api-storage.cloud.toast.com/v1/

coupon:
  notification:
    storage:
      root-email-name: coupon-email-list
      root-image-name: coupon-banner-images
      root-name-prefix: stage-
    image-root: https://rlcitca4i.cdn.toastcloud.com/